solution_aggregator:
  _target_: core.summarizers.solution_analyzer.SolutionAggregator
  summarizer:
    _target_: core.summarizers.summarizer.DocumentSummarizer
    llm:
      _target_: langchain_openai.ChatOpenAI
      model: gpt-4o-mini
      api_key: ${credentials:openai_api_key}

  solution_analyzer:
    _target_: core.summarizers.solution_analyzer.SolutionAnalyzer
    llm:
      _target_: langchain_openai.ChatOpenAI
      model: gpt-4o-mini
      api_key: ${credentials:openai_api_key}

conversation_llm:
  _target_: langchain_openai.ChatOpenAI
  model: gpt-4o-mini
  api_key: ${credentials:openai_api_key}

document_retriever:
  _target_: core.retrievers.document_retriever.WebDocumentRetriever
  search_engine: 
    _target_: core.retrievers.document_retriever.GoogleSearchEngine
    api_key: ${credentials:google_search_api_key}
    cse_id: ${credentials:google_search_cse_id}
    max_results: 3
